steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud secrets versions access latest --secret=mark-edmondson-gde-auth > inst/docker/parallel_cloudrun/plumber/auth.json
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - -f
      - Dockerfile
      - --destination
      - gcr.io/mark-edmondson-gde/cloudrun_parallel:latest
      - --context=dir:///workspace/inst/docker/parallel_cloudrun/plumber
      - --cache=true
    dir: inst/docker/parallel_cloudrun/plumber
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - -f
      - Dockerfile
      - --destination
      - gcr.io/mark-edmondson-gde/cloudrun_parallel:$BUILD_ID
      - --context=dir:///workspace/inst/docker/parallel_cloudrun/plumber
      - --cache=true
    dir: inst/docker/parallel_cloudrun/plumber
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - parallel-cloudrun
      - --image
      - gcr.io/$PROJECT_ID/cloudrun_parallel:$BUILD_ID
      - --region
      - europe-west1
      - --platform
      - managed
      - --concurrency
      - '80'
      - --port
      - default
      - --max-instances
      - default
      - --memory
      - 256Mi
      - --cpu
      - '1'
      - --set-env-vars=BQ_AUTH_FILE=auth.json,BQ_DEFAULT_PROJECT_ID=$PROJECT_ID
      - --no-allow-unauthenticated
    id: deploy cloudrun
#Generated by googleCloudRunner::cr_build_write at 2020-09-12 23:36:06
