steps:
- name: gcr.io/gcer-public/render_rmd:master
  args:
  - Rscript
  - -e
  - rmarkdown::render('scheduled_rmarkdown.Rmd', output_file = 'scheduled_rmarkdown.html')
  id: render rmd
  dir: inst/scheduled_rmarkdown/
artifacts:
  objects:
    location: 'gs://mark-edmondson-public-read'
    paths: ['inst/scheduled_rmarkdown/scheduled_rmarkdown.html']
